<a href="https://colab.research.google.com/github/bhumikasingh11/Car-Price-Prediction/blob/main/notebook%5Ccar_modeltraining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

url = "https://github.com/sumit0072/Car-Price-Prediction-Project/raw/refs/heads/main/car%20data.csv"
df = pd.read_csv(url)
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [4]:
#explore the data
print("Shape:",df.shape)
print("\nData types:\n", df.dtypes)
print("\nMissing values:\n",df.isnull().sum())
print("\nUnique Fuel_Type:", df['Fuel_Type'].unique())
print("Unique Seller_Type:", df['Seller_Type'].unique())
print("Unique Transmission:", df['Transmission'].unique())
print("Unique Owner:", df['Owner'].unique())

Shape: (301, 9)

Data types:
 Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Owner              int64
dtype: object

Missing values:
 Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

Unique Fuel_Type: ['Petrol' 'Diesel' 'CNG']
Unique Seller_Type: ['Dealer' 'Individual']
Unique Transmission: ['Manual' 'Automatic']
Unique Owner: [0 1 3]

In [5]:
#feature engineering i.e preparing the data for model
#dropping car_name , year and columns

In [6]:
current_year = 2026
df['Years_Used'] = current_year - df['Year']

df_final = df.drop(['Car_Name', 'Year'], axis=1)

df_final = pd.get_dummies(df_final, columns=['Fuel_Type', 'Seller_Type', 'Transmission'], drop_first=True)

df_final.head()
#pd.get_dummies does: it takes a text column like Fuel_Type and turns it into separate 0/1 columns,

,Selling_Price,Present_Price,Kms_Driven,Owner,Years_Used,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,12,False,True,False,True
1,4.75,9.54,43000,0,13,True,False,False,True
2,7.25,9.85,6900,0,9,False,True,False,True
3,2.85,4.15,5200,0,15,False,True,False,True
4,4.60,6.87,42450,0,12,True,False,False,True

In [7]:
#splitting the data into X,Y
# X (features) = everything we use to predict the price
# y (target) = the actual Selling_Price we're trying to predict

In [8]:
from sklearn.model_selection import train_test_split

X = df_final.drop('Selling_Price', axis=1)
y = df_final['Selling_Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

Training set size: (240, 8)
Testing set size: (61, 8)

In [9]:
#TRAIN THE RANDOM FOREST MODEL
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

print("Model trained!")

Model trained!

In [10]:
#checking how well it is trained by giving data that it never saw
from sklearn.metrics import r2_score, mean_absolute_error

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("R² Score:", r2)
print("Mean Absolute Error:", mae)

R² Score: 0.9599938850484411
Mean Absolute Error: 0.63872131147541

In [11]:
#saving as model.pkl
import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model saved as model.pkl")

Model saved as model.pkl